# Generated by Django 4.2.1 on 2024-07-04 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 4, 1, 15, 7, 673002)),
        ),
    ]
