# Generated by Django 4.2.1 on 2024-07-04 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_catalog_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 4, 1, 28, 55, 901695)),
        ),
    ]
