# Generated by Django 4.2.1 on 2024-07-05 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_catalog_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_in_dollars',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 4, 14, 49, 523949)),
        ),
    ]
